//---------------------------------------------------------------------------
// actions.h
//---------------------------------------------------------------------------
// Copyright (c) 1993-1994, Microsoft Corporation
//                 All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------
//
//  . 
//
//---------------------------------------------------------------------------
//
// Owner:  Steve Shor
// modified 03/07/94
//---------------------------------------------------------------------------

#define actionIdle                         ((ACTION) 1)
#define actionGreeting                     ((ACTION) 2)
#define actionGoodbye                      ((ACTION) 3)
#define actionBeginSpeaking                ((ACTION) 4)
#define actionClickedOn                    ((ACTION) 5)
#define actionCharacterSuccessMajor        ((ACTION) 6)
#define actionCharacterSuccessMinor        ((ACTION) 7)
#define actionCharacterFailsMajor          ((ACTION) 8)
#define actionCharacterFailsMinor          ((ACTION) 9)
#define actionAcknowledgingACancel         ((ACTION) 10)
#define actionGetAttentionMajor            ((ACTION) 11)
#define actionGetAttentionMinor            ((ACTION) 12)
#define actionSearching                    ((ACTION) 13)
#define actionFound                        ((ACTION) 14)
#define actionErrorFoundComputer           ((ACTION) 15)
#define actionErrorFoundHuman              ((ACTION) 16)
#define actionHumanSuccess                 ((ACTION) 17)
#define actionPrinting                     ((ACTION) 18)
#define actionGestureToCharactersRight     ((ACTION) 19)
#define actionAreYouSure                   ((ACTION) 20)
#define actionBirthdayCelebration          ((ACTION) 21)
#define actionWritingNotingSomething       ((ACTION) 22)
#define actionWorkingAtSomething           ((ACTION) 23)
#define actionThinking                     ((ACTION) 24)
#define actionSendingMail                  ((ACTION) 25)
#define actionListensToComputer            ((ACTION) 26)
#define actionDisappear                    ((ACTION) 31)
#define actionAppear                       ((ACTION) 32)
